name: node-badge
on:
  push:
    branches:
      - main
jobs:
  node-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.head_ref }}
      - name:  Compares Dockerfile and README.md Node.js versions and update README.md if necessary
        run: |
            DOCKERFILE_VERSION=$(cat Dockerfile | head -n 1 | sed "s/.*-alpine://")
            README_VERSION=$(cat README.md | grep node-v | sed "s/.*node-v//" | sed "s/-bright.*//")
            [[ "$DOCKERFILE_VERSION" != "$README_VERSION" ]] && sed -i -e "s|$README_VERSION-brightgreen)|$DOCKERFILE_VERSION-brightgreen)|g" README.md || exit 0
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Update README.md Node.js version badge 
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>